backend:
  name: github
  repo: mahimka1321/my-portfolio
  branch: main

media_folder: "src/assets"
public_folder: "/my-portfolio/assets"

collections:
  - name: "projects_collection"
    label: "Мои Дизайны"
    folder: "src/data"
    file: "src/data/projectsData.json"
    format: "json"
    fields:
      - name: "items"
        label: "Список проектов"
        widget: "list"
        fields:
          - { label: 'ID проекта (латиницей)', name: 'id', widget: 'string' }
          - { label: 'Главный Заголовок', name: 'title', widget: 'string' }
          - { label: 'Подзаголовок', name: 'subtitle', widget: 'string' }
          - { label: 'Описание проекта', name: 'description', widget: 'text' }
          - { label: 'Задача бизнеса', name: 'task', widget: 'text' }
          - { label: 'Результаты (по одному)', name: 'results', widget: 'list', field: {name: 'result', widget: 'string'} }
          
          # 🔥 ИЗМЕНИЛИ ТУТ:
          - name: "colors"
            label: "Палитра цветов проекта"
            widget: "list"
            field: { label: 'Выбрать цвет', name: 'colorCode', widget: 'color' }

          - { label: 'Шрифты проекта', name: 'fonts', widget: 'string' }
          - { label: 'Загрузить SVG макет', name: 'previewAsset', widget: 'file' }
          # Добавь эти поля к списку остальных полей:
          - { label: 'Теги проекта (через запятую, например: UI/UX, WEB)', name: 'tags', widget: 'list', field: {name: 'tag', widget: 'string'} }
          - { label: 'Цитата сверху (например: Чай - это тоже забота)', name: 'topQuote', widget: 'string' }
          - { label: 'Цитата слева внизу (например: уют в деталях)', name: 'leftQuote', widget: 'string' }
          - { label: 'Цитата справа внизу (например: спокойствие в клике)', name: 'rightQuote', widget: 'string' }
