backend:
  name: github
  repo: mahimka1321/my-portfolio # Твой реальный репозиторий
  branch: main

media_folder: "src/assets"
public_folder: "/my-portfolio/assets" # 🔥 ИСПРАВИЛИ ТУТ (сделали полный абсолютный путь)

collections:
  - name: "projects"
    label: "Мои Дизайны"
    folder: "src/data"
    format: "json"
    create: true
    slug: "{{id}}"
    fields:
      - { label: 'ID проекта', name: 'id', widget: 'string' }
      - { label: 'Главный Заголовок', name: 'title', widget: 'string' }
      - { label: 'Подзаголовок', name: 'subtitle', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'text' }
      - { label: 'Задача бизнеса', name: 'task', widget: 'text' }
      - { label: 'Результат (список)', name: 'results', widget: 'list' }
      - { label: 'Цвета (HEX)', name: 'colors', widget: 'list' }
      - { label: 'Шрифты', name: 'fonts', widget: 'list' }
      - { label: 'Имя файла SVG', name: 'previewAsset', widget: 'string' }
